import type { Metadata } from "next";
import { cookies } from "next/headers";
import { notFound } from "next/navigation";
import type { ReactNode } from "react";
import { NextIntlClientProvider } from "next-intl";
import { ThemeProvider } from "@/providers/theme-provider";
import { AppProvider } from "@/providers/app-provider";
import { LocaleDirectionProvider } from "@/providers/locale-direction-provider";
import { LocaleInitializer } from "@/providers/locale-initializer";
import { locales } from "@/constants/locales";
import { poppins, tajawal } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
}: {
  children: ReactNode;
}) {
  const cookieStore = await cookies();
  const localeCookie = cookieStore.get("NEXT_LOCALE")?.value;
  const locale = locales.langs.includes(localeCookie as any)
    ? (localeCookie as string)
    : locales.default;

  let messages;

  try {
    messages = (await import(`../../locales/${locale}/common.json`)).default;
  } catch (e) {
    notFound();
  }

  const fontClass = locale === "ar" ? tajawal.className : poppins.className;

  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      <AppProvider>
        <ThemeProvider>
          <LocaleDirectionProvider locale={locale} />
          <LocaleInitializer locale={locale} />
          <main className={`${fontClass} flex flex-1`}>
            {children}
          </main>
        </ThemeProvider>
      </AppProvider>
    </NextIntlClientProvider>
  );
}
